name = "aces-fullstack"
main = "src/index.ts"
compatibility_date = "2025-01-15"
[assets]
directory = "public"
[[services]]
binding = "WEB_TEST"
service = "aces-pub"
[[d1_databases]]
binding = "DB"
database_name = "aces-fullstack"
database_id = "f0ec84ce-60d6-4799-999c-be859db1ea21"


[env.prod]
name = "aces-fullstack-prod"
[env.prod.assets]
directory = "public"
[[env.prod.services]]
binding = "WEB_TEST"
service = "aces-pub-prod"
[[env.prod.d1_databases]]
binding = "DB"
database_name = "aces-fullstack-prod"
database_id = "e29c138b-06a8-41f6-9de2-012271c1f444"
