-- Migration number: 0015 	 2025-03-12T06:07:56.561Z
CREATE TABLE mod_aime_contents (
    [id] INTEGER PRIMARY KEY,
    [seq] INTEGER NOT NULL,
    [mod_uuid] TEXT NOT NULL,
    [elm] TEXT NOT NULL,
    [prompt] TEXT NOT NULL,
    [created] TEXT NOT NULL DEFAULT ((strftime('%Y-%m-%dT%H:%M:%fZ', 'now', 'utc'))),
    [updated] TEXT,
    UNIQUE (seq, mod_uuid)
);

CREATE TRIGGER update_mod_aime_contents AFTER UPDATE ON mod_aime_contents
BEGIN
    UPDATE mod_aime_contents SET updated = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now', 'utc')) WHERE id=NEW.id;
END;

INSERT INTO mod_aime_contents (seq, mod_uuid, elm, prompt) VALUES
(1, 'mRrDunGQnbQ19E5tMvA7cq', 'SLE', 'Saya cukup terbuka tentang perasaan dan emosi saya.'),
(2, 'mRrDunGQnbQ19E5tMvA7cq', 'THK', 'Ketika sedang memikirkan sesuatu, saya memblokir perasaan saya.'),
(3, 'mRrDunGQnbQ19E5tMvA7cq', 'MNO', 'Saya menjadi sedih ketika melihat ada orang diperlakukan tidak adil.'),
(4, 'mRrDunGQnbQ19E5tMvA7cq', 'IMP', 'Bagi saya, kebohongan tidak bisa dimaafkan.'),
(5, 'mRrDunGQnbQ19E5tMvA7cq', 'THK', 'Saya jarang dipengaruhi oleh perasaan ketika sedang berpikir.'),
(6, 'mRrDunGQnbQ19E5tMvA7cq', 'CPX', 'Saya bisa mengenali orang yang berlagak/sok percaya diri.'),
(7, 'mRrDunGQnbQ19E5tMvA7cq', 'IMP', 'Saya selalu berkata jujur.'),
(8, 'mRrDunGQnbQ19E5tMvA7cq', 'CAU', 'Saya tahu kenapa seseorang bisa menjadi marah.'),
(9, 'mRrDunGQnbQ19E5tMvA7cq', 'THK', 'Saya cenderung ragu dan penuh pertimbangan untuk berbagai hal.'),
(10, 'mRrDunGQnbQ19E5tMvA7cq', 'JUD', 'Saya cenderung mengabaikan yang terjadi di sekitar saya.'),
(11, 'mRrDunGQnbQ19E5tMvA7cq', 'TRA', 'Saya tahu mengapa emosi bisa berkembang dan berubah.'),
(12, 'mRrDunGQnbQ19E5tMvA7cq', 'MON', 'Dengan cepat saya bisa merubah suasana hati, sesuai dengan situasi/kondisi.'),
(13, 'mRrDunGQnbQ19E5tMvA7cq', 'TRA', 'Saya biasanya dapat memprediksi ketika emosi akan berubah.'),
(14, 'mRrDunGQnbQ19E5tMvA7cq', 'OPN', 'Saya terbuka terhadap perasaan tidak nyaman dari orang lain.'),
(15, 'mRrDunGQnbQ19E5tMvA7cq', 'SLE', 'Saya bertindak mengandalkan perasaan saya sendiri.'),
(16, 'mRrDunGQnbQ19E5tMvA7cq', 'DSC', 'Saya bisa mengenali orang yang ekspresi emosinya dibuat-buat.'),
(17, 'mRrDunGQnbQ19E5tMvA7cq', 'AOO', 'Saya biasanya bisa mengetahui apa yang dirasakan orang lain.'),
(18, 'mRrDunGQnbQ19E5tMvA7cq', 'IMP', 'Saya selalu mengakui kesalahan saya.'),
(19, 'mRrDunGQnbQ19E5tMvA7cq', 'JUD', 'Saya mempertimbangkan perasaan saya ketika membuat keputusan.'),
(20, 'mRrDunGQnbQ19E5tMvA7cq', 'SLC', 'Saya mencoba untuk menjadi positif dan ceria ketika menghadapi sebuah keputusan penting.'),
(21, 'mRrDunGQnbQ19E5tMvA7cq', 'MON', 'Saya bisa berubah pikiran, ketika mengetahui perasaan orang lain.'),
(22, 'mRrDunGQnbQ19E5tMvA7cq', 'CPX', 'Saya mendengarkan percakapan orang lain.'),
(23, 'mRrDunGQnbQ19E5tMvA7cq', 'SNS', 'Perasaan saya membantu saya fokus pada hal-hal yang memang penting.'),
(24, 'mRrDunGQnbQ19E5tMvA7cq', 'THK', 'Saya cenderung lebih mendengarkan suara hati daripada logika saya.'),
(25, 'mRrDunGQnbQ19E5tMvA7cq', 'SLC', 'Saya sering merasa kewalahan oleh suasana hati yang terjadi.'),
(26, 'mRrDunGQnbQ19E5tMvA7cq', 'MNO', 'Saya peduli dengan orang lain.'),
(27, 'mRrDunGQnbQ19E5tMvA7cq', 'SYM', 'Saya bisa tahu apakah seseorang sedang bahagia.'),
(28, 'mRrDunGQnbQ19E5tMvA7cq', 'AOO', 'Saya mampu merasakan apa yang orang lain rasakan.'),
(29, 'mRrDunGQnbQ19E5tMvA7cq', 'CPX', 'Saya tahu ketika seseorang mengalami perasaan yang campur aduk.'),
(30, 'mRrDunGQnbQ19E5tMvA7cq', 'JUD', 'Saya membaca situasi secara akurat.'),
(31, 'mRrDunGQnbQ19E5tMvA7cq', 'CAU', 'Saya memahami apa penyebab rasa malu.'),
(32, 'mRrDunGQnbQ19E5tMvA7cq', 'AOO', 'Saya bisa membaca isyarat non-verbal.'),
(33, 'mRrDunGQnbQ19E5tMvA7cq', 'IMP', 'Saya terkadang harus berbohong.'),
(34, 'mRrDunGQnbQ19E5tMvA7cq', 'SLA', 'Saya tidak begitu memperhatikan perasaan saya.'),
(35, 'mRrDunGQnbQ19E5tMvA7cq', 'SYM', 'Pada umumnya saya tahu ketika seseorang sedang marah.'),
(36, 'mRrDunGQnbQ19E5tMvA7cq', 'SYM', 'Saya bisa tahu apakah seseorang merasa jijik.'),
(37, 'mRrDunGQnbQ19E5tMvA7cq', 'TRA', 'Saya benar-benar tidak tahu bagaimana emosi bekerja.'),
(38, 'mRrDunGQnbQ19E5tMvA7cq', 'CAU', 'Saya menyadari apa yang membuat orang takut.'),
(39, 'mRrDunGQnbQ19E5tMvA7cq', 'SYM', 'Saya tidak selalu tahu, ketika seseorang sedang sedih.'),
(40, 'mRrDunGQnbQ19E5tMvA7cq', 'SLA', 'Saya biasanya menyadari apa yang saya rasakan.'),
(41, 'mRrDunGQnbQ19E5tMvA7cq', 'SLE', 'Saya sulit menggambarkan perasaan saya.'),
(42, 'mRrDunGQnbQ19E5tMvA7cq', 'CPX', 'Saya sering salah membaca perasaan orang.'),
(43, 'mRrDunGQnbQ19E5tMvA7cq', 'DSC', 'Saya tidak memahami isyarat emosional.'),
(44, 'mRrDunGQnbQ19E5tMvA7cq', 'PSO', 'Saya sering tidak mempertimbangkan perasaan saya ketika memecahkan masalah .'),
(45, 'mRrDunGQnbQ19E5tMvA7cq', 'JUD', 'Saya mengikuti naluri saya ketika harus mengambil sebuah keputusan penting.'),
(46, 'mRrDunGQnbQ19E5tMvA7cq', 'MON', 'Saya bisa dengan tiba-tiba mengubah suasana hati saya bilamana diperlukan.'),
(47, 'mRrDunGQnbQ19E5tMvA7cq', 'OPN', 'Saya memikirkan apa yang dikatakan oleh emosi saya.'),
(48, 'mRrDunGQnbQ19E5tMvA7cq', 'PSO', 'Kondisi emosi orang lain bisa mempengaruhi saya.'),
(49, 'mRrDunGQnbQ19E5tMvA7cq', 'SYM', 'Saya bisa melihat ketika orang lain terkejut.'),
(50, 'mRrDunGQnbQ19E5tMvA7cq', 'SLC', 'Saya tetap tenang dan berpikir jernih dalam situasi yang sulit (krisis).'),
(51, 'mRrDunGQnbQ19E5tMvA7cq', 'SLA', 'Saya menyadari perubahan suasana hati saya .'),
(52, 'mRrDunGQnbQ19E5tMvA7cq', 'OPN', 'Saya memahami penyebab emosi saya.'),
(53, 'mRrDunGQnbQ19E5tMvA7cq', 'TRA', 'Saya benar-benar tidak mengerti bagaimana cara emosi berubah.'),
(54, 'mRrDunGQnbQ19E5tMvA7cq', 'SNS', 'Perubahan suasana hati, memberi saya pandangan berbeda tentang sebuah situasi.'),
(55, 'mRrDunGQnbQ19E5tMvA7cq', 'SYM', 'Saya tahu ketika seseorang sedang terganggu.'),
(56, 'mRrDunGQnbQ19E5tMvA7cq', 'MON', 'Saya percaya emosi memberikan arah untuk hidup.'),
(57, 'mRrDunGQnbQ19E5tMvA7cq', 'AOO', 'Saya jarang bisa mengenali reaksi emosi orang lain.'),
(58, 'mRrDunGQnbQ19E5tMvA7cq', 'OPN', 'Saya menghindari berurusan dengan emosi yang membuat tidak nyaman.'),
(59, 'mRrDunGQnbQ19E5tMvA7cq', 'SLC', 'Saya bisa tetap jernih dan fokus di bawah tekanan.'),
(60, 'mRrDunGQnbQ19E5tMvA7cq', 'DSC', 'Saya kadang-kadang tidak memahami ekspresi dan gerak palsu.'),
(61, 'mRrDunGQnbQ19E5tMvA7cq', 'TRA', 'Saya tahu bahwa emosi mengikuti sebuah pola tertentu.'),
(62, 'mRrDunGQnbQ19E5tMvA7cq', 'SYM', 'Saya bisa tahu ketika seseorang ketakutan.'),
(63, 'mRrDunGQnbQ19E5tMvA7cq', 'SNS', 'Saya membiarkan perasaan mengambil peran utama pada beragam keputusan saya.'),
(64, 'mRrDunGQnbQ19E5tMvA7cq', 'SLE', 'Saya mampu menggambarkan apa yang saya rasakan dengan tepat.'),
(65, 'mRrDunGQnbQ19E5tMvA7cq', 'CAU', 'Saya mengerti apa yang menyebabkan kecemasan.'),
(66, 'mRrDunGQnbQ19E5tMvA7cq', 'MNO', 'Saya mampu membantu orang lain mengelola perasaan mereka.'),
(67, 'mRrDunGQnbQ19E5tMvA7cq', 'CPX', 'Saya tahu ketika orang mengalami suasana hati yang saling bertentangan.'),
(68, 'mRrDunGQnbQ19E5tMvA7cq', 'SLC', 'Saya sering mengekspresikan rasa sayang saya secara fisik.'),
(69, 'mRrDunGQnbQ19E5tMvA7cq', 'PSO', 'Insting berperan paling besar ketika saya mengambil keputusan penting.'),
(70, 'mRrDunGQnbQ19E5tMvA7cq', 'THK', 'Saya tidak membiarkan emosi saya mempengaruhi pemikiran saya.'),
(71, 'mRrDunGQnbQ19E5tMvA7cq', 'TRA', 'Saya biasanya tahu bagaimana emosi tertentu akan berkembang.'),
(72, 'mRrDunGQnbQ19E5tMvA7cq', 'OPN', 'Saya tidak mudah terpengaruh oleh perasaan orang.'),
(73, 'mRrDunGQnbQ19E5tMvA7cq', 'SLC', 'Saya mampu mengatasi beragam kegagalan dengan baik.'),
(74, 'mRrDunGQnbQ19E5tMvA7cq', 'SYM', 'Saya bisa melihat ketika seseorang sedang kecewa.'),
(75, 'mRrDunGQnbQ19E5tMvA7cq', 'CPX', 'Saya jarang memikirkan beragam alasan dibalik perasaan sesorang.'),
(76, 'mRrDunGQnbQ19E5tMvA7cq', 'SLC', 'Saya secara emosional stabil.'),
(77, 'mRrDunGQnbQ19E5tMvA7cq', 'SNS', 'Suasana hati yang berbeda membantu saya melihat masalah dari sudut yang berbeda.'),
(78, 'mRrDunGQnbQ19E5tMvA7cq', 'JUD', 'Saya membuat keputusan setelah saya memiliki semua fakta.'),
(79, 'mRrDunGQnbQ19E5tMvA7cq', 'JUD', 'Saya mencoba untuk memahami perasaan orang lain.'),
(80, 'mRrDunGQnbQ19E5tMvA7cq', 'CAU', 'Saya tertarik pada bagaimana orang lain merasakan hal-hal tertentu.'),
(81, 'mRrDunGQnbQ19E5tMvA7cq', 'PSO', 'Saya menganalisa perasaan saya untuk membantu memecahkan masalah.'),
(82, 'mRrDunGQnbQ19E5tMvA7cq', 'IMP', 'Saya tidak selalu seperti apa yang dilihat oleh orang lain.'),
(83, 'mRrDunGQnbQ19E5tMvA7cq', 'SNS', 'Saya cenderung lebih kreatif ketika saya merasa positif.'),
(84, 'mRrDunGQnbQ19E5tMvA7cq', 'SLA', 'Saya sering menganalisis bagaimana perasaan saya.'),
(85, 'mRrDunGQnbQ19E5tMvA7cq', 'MNO', 'Saya bisa membaca ekspresi wajah.'),
(86, 'mRrDunGQnbQ19E5tMvA7cq', 'DSC', 'Saya tahu ketika seseorang sedang berusaha memanipulasi saya.'),
(87, 'mRrDunGQnbQ19E5tMvA7cq', 'MON', 'Saya bukanlah orang yang mudah berubah (naik turun) suasana hatinya.'),
(88, 'mRrDunGQnbQ19E5tMvA7cq', 'SNS', 'Saya selalu berada dalam suasana hati yang sama.'),
(89, 'mRrDunGQnbQ19E5tMvA7cq', 'SLA', 'Saya jarang menyadari reaksi emosi saya.'),
(90, 'mRrDunGQnbQ19E5tMvA7cq', 'MON', 'Saya jarang memanfaatkan kondisi suasana hati saya.'),
(91, 'mRrDunGQnbQ19E5tMvA7cq', 'SLC', 'Saya tidak memperlihatkan perasaan saya pada orang lain.'),
(92, 'mRrDunGQnbQ19E5tMvA7cq', 'MON', 'Perasaan saya memberitahu ketika ada sesuatu yang salah.'),
(93, 'mRrDunGQnbQ19E5tMvA7cq', 'SLE', 'Saya cenderung memendam perasaan saya.'),
(94, 'mRrDunGQnbQ19E5tMvA7cq', 'MNO', 'Saya bisa menyadari latar belakang dari perasaan orang.'),
(95, 'mRrDunGQnbQ19E5tMvA7cq', 'JUD', 'Saya mendengarkan perasaan saya ketika membuat keputusan penting.'),
(96, 'mRrDunGQnbQ19E5tMvA7cq', 'TRA', 'Saya mengerti bagaimana emosi dapat berkembang dari waktu ke waktu.'),
(97, 'mRrDunGQnbQ19E5tMvA7cq', 'THK', 'Saya lebih suka berurusan dengan data daripada dengan perasaan.'),
(98, 'mRrDunGQnbQ19E5tMvA7cq', 'CAU', 'Saya tahu apa yang membuat orang bahagia.'),
(99, 'mRrDunGQnbQ19E5tMvA7cq', 'SNS', 'Kadang saya mengubah suasana hati, untuk mendapatkan sudut pandang yang berbeda.'),
(100, 'mRrDunGQnbQ19E5tMvA7cq', 'CAU', 'Saya tahu apa yang menyebabkan kegembiraan.'),
(101, 'mRrDunGQnbQ19E5tMvA7cq', 'AOO', 'Saya memperhatikan bahasa tubuh orang.'),
(102, 'mRrDunGQnbQ19E5tMvA7cq', 'DSC', 'Saya sering tidak sadar ketika seseorang berpura-pura atau menutupi sesuatu.'),
(103, 'mRrDunGQnbQ19E5tMvA7cq', 'CPX', 'Saya mengalami beragam jenis dan bentuk emosi.'),
(104, 'mRrDunGQnbQ19E5tMvA7cq', 'IMP', 'Saya cenderung untuk pamer jika mendapatkan kesempatan.'),
(105, 'mRrDunGQnbQ19E5tMvA7cq', 'THK', 'Saya mengikuti firasat dan perasaan saya.'),
(106, 'mRrDunGQnbQ19E5tMvA7cq', 'DSC', 'Saya biasanya tahu ketika orang mencoba menyembunyikan perasaannya.'),
(107, 'mRrDunGQnbQ19E5tMvA7cq', 'AOO', 'Saya suka memperhatikan orang.'),
(108, 'mRrDunGQnbQ19E5tMvA7cq', 'IMP', 'Saya jarang betingkah laku secara berlebihan.'),
(109, 'mRrDunGQnbQ19E5tMvA7cq', 'SLE', 'Saya bisa berbicara dengan lancar tentang perasaan saya.'),
(110, 'mRrDunGQnbQ19E5tMvA7cq', 'DSC', 'Saya bisa tertipu orang lain.'),
(111, 'mRrDunGQnbQ19E5tMvA7cq', 'SLA', 'Saya tidak pernah terpengaruh dengan perasaan saya.'),
(112, 'mRrDunGQnbQ19E5tMvA7cq', 'SLE', 'Saya menceritakan emosi saya dengan keluarga dan teman.'),
(113, 'mRrDunGQnbQ19E5tMvA7cq', 'MNO', 'Saya tidak ingin terlibat dalam masalah orang lain.'),
(114, 'mRrDunGQnbQ19E5tMvA7cq', 'DSC', 'Saya bisa tahu ketika seseorang tersenyum palsu.'),
(115, 'mRrDunGQnbQ19E5tMvA7cq', 'JUD', 'Saya tidak membiarkan perasaan saya mempengaruhi penalaran saya.'),
(116, 'mRrDunGQnbQ19E5tMvA7cq', 'SLA', 'Saya sering mengabaikan perasaan saya.'),
(117, 'mRrDunGQnbQ19E5tMvA7cq', 'PSO', 'Saya menggunakan perasaan untuk memahami beragam aspek dari sebuah situasi.'),
(118, 'mRrDunGQnbQ19E5tMvA7cq', 'MON', 'Bilamana diperlukan, saya bisa membebaskan diri dari suasana hati saat itu .'),
(119, 'mRrDunGQnbQ19E5tMvA7cq', 'IMP', 'Saya terkadang memanfaatkan pujian dan sanjungan untuk bisa maju.'),
(120, 'mRrDunGQnbQ19E5tMvA7cq', 'SLA', 'Saya cenderung mengetahui emosi apa yang saya rasakan.'),
(121, 'mRrDunGQnbQ19E5tMvA7cq', 'PSO', 'Saya sering tidak mempertimbangkan apa yang dipikirkan orang lain.'),
(122, 'mRrDunGQnbQ19E5tMvA7cq', 'CAU', 'Saya bisa mengerti mengapa orang jadi agresif.'),
(123, 'mRrDunGQnbQ19E5tMvA7cq', 'PSO', 'Analisis saya terhadap suatu masalah jarang dipengaruhi oleh perasaan saya.'),
(124, 'mRrDunGQnbQ19E5tMvA7cq', 'MNO', 'Saya peka terhadap perasaan orang lain.'),
(125, 'mRrDunGQnbQ19E5tMvA7cq', 'OPN', 'Saya memahami bagaimana perasaan mempengaruhi perilaku saya.'),
(126, 'mRrDunGQnbQ19E5tMvA7cq', 'AOO', 'Saya tidak terlalu peduli tentang perasaan orang lain.'),
(127, 'mRrDunGQnbQ19E5tMvA7cq', 'TRA', 'Saya sering lupa bahwa suasana hati bisa berubah seiring perubahan situasi dan kondisi.'),
(128, 'mRrDunGQnbQ19E5tMvA7cq', 'MNO', 'Saya berempati dengan orang-orang yang sedang dihimpit masalah.'),
(129, 'mRrDunGQnbQ19E5tMvA7cq', 'OPN', 'Saya biasanya merasa, ketika ada sesuatu yang salah.'),
(130, 'mRrDunGQnbQ19E5tMvA7cq', 'CPX', 'Saya sering tidak menyadari kondisi emosi orang lain.'),
(131, 'mRrDunGQnbQ19E5tMvA7cq', 'PSO', 'Saya mengijinkan perasaan saya mempengaruhi keputusan saya.'),
(132, 'mRrDunGQnbQ19E5tMvA7cq', 'THK', 'Saya jarang dikuasai oleh perasaan, ketika sedang memikirkan sesuatu.'),
(133, 'mRrDunGQnbQ19E5tMvA7cq', 'SLE', 'Saya sering tidak bisa menemukan kata yang tepat untuk menggambarkan perasaan saya.'),
(134, 'mRrDunGQnbQ19E5tMvA7cq', 'AOO', 'Saya suka mengamati orang.'),
(135, 'mRrDunGQnbQ19E5tMvA7cq', 'SNS', 'Saya bukan orang yang moody, yang suasana hatinya sering berubah ubah.'),
(136, 'mRrDunGQnbQ19E5tMvA7cq', 'OPN', 'Saya tahu ketika seseorang berusaha menutup-nutupi sesuatu dari saya.');