-- Migration number: 0018 	 2025-03-12T06:08:56.394Z
CREATE TABLE mod_csi_contents (
    [id] INTEGER PRIMARY KEY,
    [mod_uuid] TEXT NOT NULL,
    [seq] INTEGER NOT NULL,
    [trend] TEXT NOT NULL,
    [focus] TEXT NOT NULL,
    [action] TEXT NOT NULL,
    [prompt] TEXT NOT NULL,
    [created] TEXT NOT NULL DEFAULT ((strftime('%Y-%m-%dT%H:%M:%fZ', 'now', 'utc'))),
    [updated] TEXT,
    UNIQUE (seq, mod_uuid)
);

CREATE TRIGGER update_mod_csi_contents AFTER UPDATE ON mod_csi_contents
BEGIN
    UPDATE mod_csi_contents SET updated = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now', 'utc')) WHERE id=NEW.id;
END;

INSERT INTO mod_csi_contents (id, mod_uuid, seq, trend, focus, action, prompt) VALUES
    (1, '9LXiqv2vxZpc3JHrwzoC3h', 1, 'ENG', 'PRO', 'PS', 'Saya berkonsentrasi pada apa yang harus dilakukan untuk langkah selanjutnya.'),
    (2, '9LXiqv2vxZpc3JHrwzoC3h', 2, 'ENG', 'PRO', 'CR', 'Saya mencoba untuk mendapatkan sudut pandang lain terhadap situasi tersebut.'),
    (3, '9LXiqv2vxZpc3JHrwzoC3h', 3, 'ENG', 'EMO', 'EE', 'Saya mencari cara untuk mengeluarkan kesumpekan saya.'),
    (4, '9LXiqv2vxZpc3JHrwzoC3h', 4, 'ENG', 'EMO', 'SS', 'Saya mendapat simpati dan pengertian dari seseorang.'),
    (5, '9LXiqv2vxZpc3JHrwzoC3h', 5, 'DIS', 'PRO', 'PA', 'Saya tidur lebih banyak dari biasanya.'),
    (6, '9LXiqv2vxZpc3JHrwzoC3h', 6, 'DIS', 'PRO', 'WT', 'Saya berharap masalah itu akan selesai dengan sendirinya.'),
    (7, '9LXiqv2vxZpc3JHrwzoC3h', 7, 'DIS', 'EMO', 'SC', 'Saya pikir kalau saya tidak seceroboh itu, mungkin hal ini tidak akan terjadi tidak akan terjadi.'),
    (8, '9LXiqv2vxZpc3JHrwzoC3h', 8, 'DIS', 'EMO', 'SW', 'Saya simpan perasaan saya untuk diri sendiri.'),
    (9, '9LXiqv2vxZpc3JHrwzoC3h', 9, 'ENG', 'PRO', 'PS', 'Saya lakukan apapun yang bisa membantu mempercepat selesainya masalah.'),
    (10, '9LXiqv2vxZpc3JHrwzoC3h', 10, 'ENG', 'PRO', 'CR', 'Saya yakinkan diri sendiri, setiap kejadian pasti ada makna tersendiri dibaliknya.'),
    (11, '9LXiqv2vxZpc3JHrwzoC3h', 11, 'ENG', 'EMO', 'EE', 'Saya lakukan sesuatu, dalam rangka keluar dari situasi ini.'),
    (12, '9LXiqv2vxZpc3JHrwzoC3h', 12, 'ENG', 'EMO', 'SS', 'Saya  menemukan seorang pendengar yang baik.'),
    (13, '9LXiqv2vxZpc3JHrwzoC3h', 13, 'DIS', 'PRO', 'PA', 'Saya bersikap seolah tak terjadi suatu apapun.'),
    (14, '9LXiqv2vxZpc3JHrwzoC3h', 14, 'DIS', 'PRO', 'WT', 'Saya berharap akan terjadi sebuah keajaiban '),
    (15, '9LXiqv2vxZpc3JHrwzoC3h', 15, 'DIS', 'EMO', 'SC', 'Saya menyadari, saya sendiri yang menyebabkan masalah ini berlarut larut.'),
    (16, '9LXiqv2vxZpc3JHrwzoC3h', 16, 'DIS', 'EMO', 'SW', 'Saya lebih banyak menghabiskan waktu sendirian.'),
    (17, '9LXiqv2vxZpc3JHrwzoC3h', 17, 'ENG', 'PRO', 'PS', 'Saya bertahan dan berjuang untuk mencapai solusi yang saya inginkan.'),
    (18, '9LXiqv2vxZpc3JHrwzoC3h', 18, 'ENG', 'PRO', 'CR', 'Saya katakan pada diri saya sendiri beragam hal yang bisa membuat saya merasa lebih baik.'),
    (19, '9LXiqv2vxZpc3JHrwzoC3h', 19, 'ENG', 'EMO', 'EE', 'Saya biarkan emosi saya keluar.'),
    (20, '9LXiqv2vxZpc3JHrwzoC3h', 20, 'ENG', 'EMO', 'SS', 'Saya ceritakan bagaimana perasaan saya pada seseorang.'),
    (21, '9LXiqv2vxZpc3JHrwzoC3h', 21, 'DIS', 'PRO', 'PA', 'Saya coba melupakan semuanya.'),
    (22, '9LXiqv2vxZpc3JHrwzoC3h', 22, 'DIS', 'PRO', 'WT', 'Saya berharap untuk tidak terlibat dengan situasi tersebut.'),
    (23, '9LXiqv2vxZpc3JHrwzoC3h', 23, 'DIS', 'EMO', 'SC', 'Saya menyalahkan diri sendiri.'),
    (24, '9LXiqv2vxZpc3JHrwzoC3h', 24, 'DIS', 'EMO', 'SW', 'Saya menghindar dari keluarga dan teman teman.'),
    (25, '9LXiqv2vxZpc3JHrwzoC3h', 25, 'ENG', 'PRO', 'PS', 'Saya membuat rencana tindakan dan mennjalankannya.'),
    (26, '9LXiqv2vxZpc3JHrwzoC3h', 26, 'ENG', 'PRO', 'CR', 'Saya mencoba realistis, melakukan yang terbaik dari yang masih bisa dilakukan.'),
    (27, '9LXiqv2vxZpc3JHrwzoC3h', 27, 'ENG', 'EMO', 'EE', 'Saya mengumbar perasaan saya, dalam rangka mengurangi stress.'),
    (28, '9LXiqv2vxZpc3JHrwzoC3h', 28, 'ENG', 'EMO', 'SS', 'Saya lebih banyak bergaul dengan orang yang saya sukai.'),
    (29, '9LXiqv2vxZpc3JHrwzoC3h', 29, 'DIS', 'PRO', 'PA', 'Saya tidak mau terpengaruh, saya tidak mau memikirkannya terlalu dalam.'),
    (30, '9LXiqv2vxZpc3JHrwzoC3h', 30, 'DIS', 'PRO', 'WT', 'Saya berharap situasi tersebut akan selesai dengan sendirinya.'),
    (31, '9LXiqv2vxZpc3JHrwzoC3h', 31, 'DIS', 'EMO', 'SC', 'Saya mengkritik diri saya sendiri atas semua yang sudah terjadi.'),
    (32, '9LXiqv2vxZpc3JHrwzoC3h', 32, 'DIS', 'EMO', 'SW', 'Saya menghindar dari orang  orang.'),
    (33, '9LXiqv2vxZpc3JHrwzoC3h', 33, 'ENG', 'PRO', 'PS', 'Saya selesaikan secara personal,  berhadapan langsung dengan masalah tersebut.'),
    (34, '9LXiqv2vxZpc3JHrwzoC3h', 34, 'ENG', 'PRO', 'CR', 'Saya menganalisa tentang bagaimana dan mengapa semua ini bisa terjadi.'),
    (35, '9LXiqv2vxZpc3JHrwzoC3h', 35, 'ENG', 'EMO', 'EE', 'Terkadang saya sengaja mengeluarkan isi hati saya.'),
    (36, '9LXiqv2vxZpc3JHrwzoC3h', 36, 'ENG', 'EMO', 'SS', 'Saya ngobrol dengan orang yang dekat dengan saya.'),
    (37, '9LXiqv2vxZpc3JHrwzoC3h', 37, 'DIS', 'PRO', 'PA', 'Saya bersikap bahwa itu masalah orang lain, bukan masalah saya.'),
    (38, '9LXiqv2vxZpc3JHrwzoC3h', 38, 'DIS', 'PRO', 'WT', 'Saya berharap kejadian itu tidak pernah terjadi.'),
    (39, '9LXiqv2vxZpc3JHrwzoC3h', 39, 'DIS', 'EMO', 'SC', 'Karena semua itu salah saya sendiri, saya harus menanggung segala resikonya.'),
    (40, '9LXiqv2vxZpc3JHrwzoC3h', 40, 'DIS', 'EMO', 'SW', 'Saya tidak memberitahu orng lain tentang masalah tersebut.'),
    (41, '9LXiqv2vxZpc3JHrwzoC3h', 41, 'ENG', 'PRO', 'PS', 'Saya tahu yang harus dilakukan dan berusaha sekuat tenaga menyelesaikannya.'),
    (42, '9LXiqv2vxZpc3JHrwzoC3h', 42, 'ENG', 'PRO', 'CR', 'Saya meyakinkan diri saya bahwa semua itu tidak seberat yang dikira.'),
    (43, '9LXiqv2vxZpc3JHrwzoC3h', 43, 'ENG', 'EMO', 'EE', 'Saya mengumbar emosi saya.'),
    (44, '9LXiqv2vxZpc3JHrwzoC3h', 44, 'ENG', 'EMO', 'SS', 'Saya biarkan teman-teman saya membantu.'),
    (45, '9LXiqv2vxZpc3JHrwzoC3h', 45, 'DIS', 'PRO', 'PA', 'Saya menghindari orang yang menyebabkan masalah terjadi.'),
    (46, '9LXiqv2vxZpc3JHrwzoC3h', 46, 'DIS', 'PRO', 'WT', 'Saya berharap dan berandai-andai, seharusnya kejadiannya tidak seperti itu.'),
    (47, '9LXiqv2vxZpc3JHrwzoC3h', 47, 'DIS', 'EMO', 'SC', 'Saya menyadari dan selalu menceramahi diri sendiri, bahwa semua itu karena kesalahan saya.'),
    (48, '9LXiqv2vxZpc3JHrwzoC3h', 48, 'DIS', 'EMO', 'SW', 'Saya cukup sering meluangkan waktu untuk sendiri.'),
    (49, '9LXiqv2vxZpc3JHrwzoC3h', 49, 'ENG', 'PRO', 'PS', 'Melakukan beragam cara baru dan tidak biasa, karena masalahnya rumit dan ruwet.'),
    (50, '9LXiqv2vxZpc3JHrwzoC3h', 50, 'ENG', 'PRO', 'CR', 'Diam dan tenang sejenak, mencoba melihat situasi tersebut dari beragam perspektif.'),
    (51, '9LXiqv2vxZpc3JHrwzoC3h', 51, 'ENG', 'EMO', 'EE', 'Rasanya kepala mau pecah, dan akhirnya emosi saya jebol tidak mampu ditahan '),
    (52, '9LXiqv2vxZpc3JHrwzoC3h', 52, 'ENG', 'EMO', 'SS', 'Menghubungi teman dan anggota keluarga yang disegani, lalu meminta nasehat mereka.'),
    (53, '9LXiqv2vxZpc3JHrwzoC3h', 53, 'DIS', 'PRO', 'PA', 'Saya mencoba santai, tidak mau terlalu serius memikirkannya.'),
    (54, '9LXiqv2vxZpc3JHrwzoC3h', 54, 'DIS', 'PRO', 'WT', 'Saya berharap kalau saya cukup sabar, mestinya masalah akan selesai dengan sendirinya.'),
    (55, '9LXiqv2vxZpc3JHrwzoC3h', 55, 'DIS', 'EMO', 'SC', 'Saya menyesali diri sendiri karena membiarkan semua itu terjadi.'),
    (56, '9LXiqv2vxZpc3JHrwzoC3h', 56, 'DIS', 'EMO', 'SW', 'Saya simpan perasaan dan pikiran saya untuk diri sendiri.'),
    (57, '9LXiqv2vxZpc3JHrwzoC3h', 57, 'ENG', 'PRO', 'PS', 'Saya bekerja keras menyelesaikannya langsung ditempat masalah tersebut terjadi.'),
    (58, '9LXiqv2vxZpc3JHrwzoC3h', 58, 'ENG', 'PRO', 'CR', 'Saya mencoba merinci dan memilah-nya sehingga tidak terasa terlalu berat masalahnya.'),
    (59, '9LXiqv2vxZpc3JHrwzoC3h', 59, 'ENG', 'EMO', 'EE', 'Saya mencoba berdialog dengan perasaan saya, lalu mengeluarkannya dengan lega.'),
    (60, '9LXiqv2vxZpc3JHrwzoC3h', 60, 'ENG', 'EMO', 'SS', 'Saya luangkan waktu bercengkerama dengan teman-teman saya.'),
    (61, '9LXiqv2vxZpc3JHrwzoC3h', 61, 'DIS', 'PRO', 'PA', 'Daripada selalu sedih kalau mengingatnya, saya mencoba untuk tidak memikirkannya lagi.'),
    (62, '9LXiqv2vxZpc3JHrwzoC3h', 62, 'DIS', 'PRO', 'WT', 'Saya sering berandai-andai bahwa saya bisa mencegah hal tersebut terjadi.'),
    (63, '9LXiqv2vxZpc3JHrwzoC3h', 63, 'DIS', 'EMO', 'SC', 'Semua kesalahan saya, dan saya menerima segala resiko dan penderitaannya.'),
    (64, '9LXiqv2vxZpc3JHrwzoC3h', 64, 'DIS', 'EMO', 'SW', 'Saya tidak membiarkan keluarga dan teman-teman tahu apa yang sebenarnya terjadi.'),
    (65, '9LXiqv2vxZpc3JHrwzoC3h', 65, 'ENG', 'PRO', 'PS', 'Saya berusaha mati-matian menyelesaikan masalah tersebut.'),
    (66, '9LXiqv2vxZpc3JHrwzoC3h', 66, 'ENG', 'PRO', 'CR', 'Saya tak pernah menyerah sampai akhirnya menemukan secercah harapan untuk solusinya.'),
    (67, '9LXiqv2vxZpc3JHrwzoC3h', 67, 'ENG', 'EMO', 'EE', 'Sayta benar benar marah dan emosi.'),
    (68, '9LXiqv2vxZpc3JHrwzoC3h', 68, 'ENG', 'EMO', 'SS', 'Saya ngobrol dengan orang yang pernah mengalami situasi yang kurang lebih sama.'),
    (69, '9LXiqv2vxZpc3JHrwzoC3h', 69, 'DIS', 'PRO', 'PA', 'Saya tidak mau memikirkan ataupun malakukan sesuatu berkenaan dengan masalah tersebut.'),
    (70, '9LXiqv2vxZpc3JHrwzoC3h', 70, 'DIS', 'PRO', 'WT', 'Saya berkhayal tentang sesuatu yang fantastik, yang membuat saya merasa lebih baik.'),
    (71, '9LXiqv2vxZpc3JHrwzoC3h', 71, 'DIS', 'EMO', 'SC', 'Saya katakan pada diri saya sendiri betapa bodohnya saya.'),
    (72, '9LXiqv2vxZpc3JHrwzoC3h', 72, 'DIS', 'EMO', 'SW', 'Saya tidak membiarkan siapapun untuk mengetahui bagaimana perasaan saya.');