-- Migration number: 0035 	 2025-03-14T06:51:56.977Z
DROP TABLE IF EXISTS mod_ca_elements; CREATE TABLE mod_ca_elements (
	[id] INTEGER PRIMARY KEY,
	[name] TEXT NOT NULL,
	[domain] TEXT NOT NULL,
	[description] TEXT NOT NULL DEFAULT '',
	[created] TEXT NOT NULL DEFAULT ((strftime('%Y-%m-%dT%H:%M:%fZ', 'now', 'utc'))),
	[updated] TEXT
);

CREATE TRIGGER update_mod_ca_elements AFTER UPDATE ON mod_ca_elements
    BEGIN UPDATE mod_ca_elements SET updated = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now', 'utc')) WHERE id=NEW.id;
END;

INSERT INTO mod_ca_elements (id, name, description, domain) VALUES
    (1, 'Self-Awareness', 'Kemampuan untuk mengenali dan memahami emosi yang dirasakan, serta mengetahui bagaimana emosi tersebut mempengaruhi pikiran, perasaan, dan tindakan seseorang.', 'EMO'),
    (2, 'Self-Regulation', 'Kemampuan untuk mengendalikan dan mengatur emosi diri sendiri, sehingga dapat menangani situasi yang menantang dengan tenang dan bijaksana, serta mampu menyesuaikan diri dengan perubahan lingkungan.', 'EMO'),
    (3, 'Self-Control GPQ', 'Kemampuan untuk mengendalikan dan mengatur emosi diri sendiri, sehingga dapat menangani situasi yang menantang dengan tenang dan bijaksana, serta mampu menyesuaikan diri dengan perubahan lingkungan.', 'EMO'),
    (4, 'Stress Management', 'Kemampuan untuk mengenali, mengatasi, dan mengurangi stres dalam kehidupan sehari-hari, baik di tempat kerja maupun di luar tempat kerja. Pengendalian stres melibatkan teknik relaksasi, pemikiran positif, dan strategi penyesuaian untuk menjaga kesehatan emosional dan fisik.', 'EMO'),
    (5, 'Social Recognition', 'Kemampuan untuk mengenali dan memahami emosi orang lain melalui informasi verbal/non verbal, berbagai isyarat, seperti ekspresi wajah, bahasa tubuh, dan nada suara.', 'EMO'),
    (6, 'Social Response', 'Kemampuan untuk menengarai, memahami dan merespon situasi dari sudut pandang orang lain, serta menghargai perasaan, pikiran, dan pengalaman mereka, memastikan dan menunjukkan bahwa emosi mereka valid dan penting untuk dipahami.', 'EMO'),
    (7, 'Openness', 'Kemampuan untuk menerima dan mempertimbangkan ide, pendapat, dan perspektif yang berbeda.', 'SELF'),
    (8, 'Mental Flexibility', 'Kemampuan untuk berpikir secara terbuka dan menerima perubahan, serta bersedia untuk mengubah pendekatan atau ide ketika situasi memerlukan.', 'SELF'),
    (9, 'Self-Introspection', 'Kemampuan menilai diri sendiri secara kritis, termasuk kekuatan, kelemahan, dan bias, serta pengaruhnya pada pengambilan keputusan dan tindakan.', 'SELF'),
    (10, 'Ambiguity Tolerance', 'Kemampuan untuk merasa nyaman dalam menghadapi ketidakpastian dan situasi yang tidak jelas, serta mampu bekerja efektif dalam kondisi tersebut.', 'SELF'),
    (11, 'Work-Life Balance', 'Kemampuan mempertahankan keseimbangan antara kehidupan profesional dan pribadi, meliputi pengaturan waktu, prioritas, dan komitmen yang sehat.', 'SELF'),
    (12, 'Resilience (Kemembalan)', 'Kemampuan untuk cepat pulih mengatasi kegagalan, rintangan, tekanan, melibatkan ketahanan emosional, fleksibilitas, dan kemampuan untuk belajar dari kesalahan.', 'SELF'),
    (13, 'Persistence (Ketekunan)', 'Kemampuan untuk terus berusaha mencapai tujuan meskipun dihadapkan dengan kesulitan atau penundaan dalam mencapai sukses, fokus pada aksi dan upaya yang berkelanjutan.', 'SELF'),
    (14, 'Determination (Tekad)', 'Kemampuan kekuatan mental dan kemauan untuk mencapai tujuan, tidak peduli seberapa sulit rintangannya, fokus pada motivasi intrinsik yang kuat dan hasil.', 'SELF'),
    (15, 'Initiative', 'Kemampuan untuk mengambil tindakan proaktif dan mengidentifikasi peluang tanpa menunggu perintah atau arahan dari orang lain, melibatkan antusiasme, kreativitas, dan keinginan untuk mencoba hal-hal baru serta menghadapi tantangan.', 'SELF'),
    (16, 'Independence', 'Kemampuan bekerja dan membuat keputusan secara mandiri, tanpa tergantung pada bantuan atau arahan orang lain, keyakinan pada kemampuan diri, tanggung jawab atas tindakan dan kemampuan mengelola secara efisien.', 'SELF'),
    (17, 'Goal Setting', 'Kemampuan menetapkan, melacak, dan mencapai tujuan yang bermakna dan realistis, melibatkan pemahaman apa yang ingin dicapai, penentuan langkah-langkah konkret dan komitmen.', 'SELF'),
    (18, 'Solution-Oriented', 'Kemampuan untuk mencari dan mengembangkan solusi yang efektif ketika menghadapi perubahan dan ketidakpastian, serta memanfaatkan peluang yang muncul dari situasi yang dinamis.', 'SELF'),
    (19, 'Results-Oriented', 'Fokus pada pencapaian hasil yang diinginkan dan melampaui standar kinerja yang ada, melibatkan komitmen untuk mengukur kemajuan, menganalisis kesenjangan, dan mengambil tindakan.', 'SELF'),
    (20, 'Curiosity', 'Sikap yang terus-menerus ingin mengetahui, mempelajari, dan mengeksplorasi hal-hal baru, menggali lebih dalam untuk memahami topik atau situasi.', 'SELF'),
    (21, 'Knowledge Seeking', 'Usaha yang aktif dan terus-menerus untuk memperoleh pengetahuan baru, baik melalui pembelajaran formal maupun informal.', 'SELF'),
    (22, 'Experimentation', 'Kemampuan untuk mencoba pendekatan baru, teknik, atau alat dalam rangka mencari solusi yang lebih baik, belajar dari kegagalan dan kesuksesan.', 'SELF'),
    (23, 'Argumentation', 'Kemampuan untuk menggunakan argumen, logika dan alasan dalam mengevaluasi informasi dan membuat keputusan.', 'COG'),
    (24, 'Abstract Reasoning', 'Kemampuan untuk memahami konsep dan ide yang tidak terikat secara langsung oleh pengalaman sensoris dan konkret. Ini melibatkan kemampuan untuk melihat pola dan hubungan, berpikir secara hipotetis, dan menguasai konsep yang kompleks dan abstrak.', 'COG'),
    (25, 'Information Synthesis', 'Kemampuan untuk menggabungkan informasi dari berbagai sumber, baik konkret maupun abstrak, untuk menciptakan pemahaman yang lebih dalam atau mencari solusi yang lebih baik untuk suatu masalah.', 'COG'),
    (26, 'Evidence Evaluation', 'Kemampuan untuk menilai kualitas dan relevansi bukti sebelum menggunakannya dalam pengambilan keputusan.', 'COG'),
    (27, 'Conclusion Drawing', 'Kemampuan untuk mengambil kesimpulan yang tepat dan relevan berdasarkan analisis dan interpretasi data.', 'COG'),
    (28, 'Bias Identification', 'Kemampuan untuk mengidentifikasi dan mengakui bias dalam informasi, proses pemikiran, dan perspektif orang lain serta diri sendiri.', 'COG'),
    (29, 'Concept Understanding', 'Kemampuan untuk memahami konsep-konsep abstrak dan penerapan pemahaman tersebut dalam situasi nyata.', 'COG'),
    (30, 'Concept Application', 'Kemampuan untuk menggabungkan konsep-konsep yang telah dipahami dalam menghadapi situasi baru, dan menciptakan solusi yang efektif.', 'COG'),
    (31, 'Problem Identification', 'Kemampuan untuk mengenali dan mendefinisikan masalah yang dihadapi serta menentukan penyebab utamanya.', 'COG'),
    (32, 'Problem Anticipation', 'Kemampuan untuk mengantisipasi dan mengidentifikasi potensi masalah sebelum mereka terjadi, memungkinkan tindakan pencegahan yang efektif.', 'COG'),
    (33, 'Problem Analysis', 'Kemampuan untuk menganalisis masalah secara sistematis, mengumpulkan informasi yang relevan, dan mengidentifikasi akar penyebab masalah.', 'COG'),
    (34, 'Risk Management', 'Kemampuan untuk mengidentifikasi, mengevaluasi, dan mengelola risiko yang mungkin mempengaruhi pencapaian tujuan atau operasi suatu organisasi.', 'COG'),
    (35, 'Analisis SWOT (SWOT Analysis)', 'Kemampuan untuk menganalisis kekuatan, kelemahan, peluang, dan ancaman organisasi atau situasi tertentu untuk mendukung pengambilan keputusan strategis.', 'COG'),
    (36, 'PESTEL Analysis', 'Kemampuan untuk menganalisis faktor politik, ekonomi, sosial, teknologi, lingkungan, dan hukum yang mempengaruhi organisasi atau situasi tertentu.', 'COG'),
    (37, 'Alternative Evaluation', 'Kemampuan untuk mengevaluasi alternatif yang berbeda berdasarkan analisis data dan memilih opsi terbaik.', 'COG'),
    (38, 'Thinking Outside the Box', 'Kemampuan untuk melihat masalah atau situasi dari sudut pandang yang berbeda, dan mencari solusi yang tidak konvensional atau inovatif.', 'CREA'),
    (39, 'Ideation', 'Kemampuan untuk menghasilkan sejumlah ide baru, unik, dan bervariasi dalam menghadapi masalah atau tantangan.', 'CREA'),
    (40, 'Free Association', 'Kemampuan untuk menghubungkan ide-ide yang tampaknya tidak terkait, dengan tujuan untuk menghasilkan ide-ide baru dan kreatif.', 'CREA'),
    (41, 'Systems Thinking', 'kemampuan untuk melihat dan memahami hubungan antara bagian-bagian dari sistem dan bagaimana mereka saling berinteraksi dan berkontribusi pada sistem secara keseluruhan. Berpikir sistemik adalah pendekatan holistik yang melihat sistem sebagai suatu kesatuan, bukan hanya sebagai kumpulan bagian yang terisolasi.', 'STRAT'),
    (42, 'Vision Development', 'Kemampuan untuk menciptakan dan menggambarkan visi jangka panjang yang inspiratif dan menarik, yang dapat membimbing organisasi atau tim menuju kesuksesan di masa depan.', 'STRAT'),
    (43, 'Trend Analysis', 'kemampuan untuk memahami dan memprediksi arah perubahan dalam data sepanjang waktu dan memahami dampak dari tren tersebut terhadap situasi atau organisasi saat ini dan masa depan', 'STRAT'),
    (44, 'Ethical Awareness', 'Kemampuan untuk mengenali dan memahami nilai-nilai etika, norma, dan standar yang berlaku dalam suatu organisasi, profesi, atau masyarakat, serta menjadikannya sebagai pedoman dalam pengambilan keputusan dan tindakan.', 'NORM'),
    (45, 'Honesty and Transparency', 'Komitmen untuk selalu bersikap jujur, terbuka, dan transparan dalam semua tindakan dan komunikasi, baik dalam hubungan internal maupun eksternal, sehingga dapat membangun kepercayaan dan kredibilitas.', 'NORM'),
    (46, 'Value Alignment', 'Kesesuaian nilai-nilai, keyakinan, dan tindakan pribadi dengan nilai-nilai, visi, dan misi organisasi, serta berkomitmen untuk mendukung dan mewujudkan tujuan organisasi.', 'NORM'),
    (47, 'Adherence to Principles', 'Kemampuan untuk berpegang teguh pada prinsip-prinsip etika dan integritas dalam situasi yang sulit atau menantang, serta mampu menegakkan standar etika yang tinggi dalam diri sendiri dan orang lain.', 'NORM'),
    (48, 'Environmental Sustainability', 'Komitmen untuk menjaga dan melindungi lingkungan, serta mengadopsi praktik bisnis yang ramah lingkungan dan berkelanjutan, dengan tujuan untuk menciptakan keseimbangan antara pertumbuhan ekonomi, kesejahteraan sosial, dan kelestarian lingkungan.', 'NORM'),
    (49, 'Social Responsibility', 'Kesadaran akan dampak tindakan dan keputusan yang diambil terhadap masyarakat dan lingkungan, serta berkomitmen untuk berkontribusi pada kesejahteraan sosial dan pembangunan yang berkelanjutan.', 'NORM'),
    (50, 'Visual Communication', 'Kemampuan untuk menyampaikan temuan dan wawasan yang diperoleh dari visualisasi data kepada audiens yang dituju, dengan cara yang jelas, ringkas, dan persuasif, serta memastikan bahwa pesan yang disampaikan mudah dipahami dan relevan dengan kepentingan audiens.', 'COM'),
    (51, 'Vision & Strategy Communication', 'Kemampuan untuk menyampaikan visi dan strategi kepada anggota tim atau organisasi secara jelas, persuasif, dan inspiratif, sehingga mereka dapat memahami dan mendukung tujuan bersama.', 'COM'),
    (52, 'Information Sharing', 'Kemampuan untuk berbagi informasi, pengetahuan, dan sumber daya dengan orang lain dalam jaringan secara efektif.', 'COM'),
    (53, 'Speaking Skills', 'Kemampuan untuk menyampaikan informasi dan ide secara jelas dan efektif melalui lisan.', 'COM'),
    (54, 'Effective Response', 'Kemampuan untuk memberikan tanggapan yang efektif dan tepat waktu terhadap komunikasi dari orang lain.', 'COM'),
    (55, 'Communication Skills', 'Kemampuan untuk menyesuaikan gaya komunikasi sesuai dengan konteks dan audiens yang berbeda, mampu menyampaikan informasi dengan jelas dan efektif, serta memahami perspektif dan kebutuhan orang lain.', 'COM'),
    (56, 'Active Listening', 'Kemampuan untuk secara efektif menerima dan memahami informasi yang disampaikan oleh orang lain.', 'COM'),
    (57, 'Writing Skills', 'Kemampuan untuk menyampaikan informasi dan ide secara jelas dan efektif melalui tulisan.', 'COM'),
    (58, 'Relationships Building', 'Kemampuan untuk menjalin hubungan yang kuat dan saling menguntungkan dengan individu dan kelompok dalam konteks profesional.', 'SOC'),
    (59, 'Social Mapping', 'Kemampuan untuk mengenali dan memahami perspektif, kebutuhan, dan motivasi orang lain, sehingga dapat berkomunikasi dan mempengaruhi mereka dengan lebih efektif.', 'SOC'),
    (60, 'Social Mapping GPQ', 'Kemampuan untuk mengenali dan memahami perspektif, kebutuhan, dan motivasi orang lain, sehingga dapat berkomunikasi dan mempengaruhi mereka dengan lebih efektif.', 'SOC'),
    (61, 'Situational Mapping', 'Kemampuan untuk memahami dan mengevaluasi situasi yang sedang dihadapi, termasuk dinamika tim, lingkungan, dan tantangan, sehingga pemimpin dapat membuat keputusan yang tepat dan mengarahkan tim dengan cara yang paling efektif.', 'SOC'),
    (62, 'Team Mapping', 'Kemampuan untuk mengenali kebutuhan, motivasi, kekuatan, dan kelemahan anggota tim, serta memahami dinamika kelompok.', 'SOC'),
    (63, 'Recognizing Achievements', 'Kemampuan untuk mengakui dan menghargai prestasi, usaha, dan kontribusi positif yang dibuat oleh anggota tim atau individu, sehingga mereka merasa dihargai dan termotivasi.', 'SOC'),
    (64, 'Equality and Diversity', 'Kemampuan untuk mendorong kesetaraan dan keberagaman dalam tim, memastikan setiap anggota diperlakukan secara adil dan dihormati.', 'SOC'),
    (65, 'Conflict Identification', 'Kemampuan untuk mengenali dan mengidentifikasi konflik yang muncul dalam tim atau antar individu.', 'SOC'),
    (66, 'Differencies-Value', 'Kemampuan untuk menghargai dan mengakui keunikan individu, termasuk latar belakang, budaya, dan perspektif yang berbeda.', 'SOC'),
    (67, 'Differencies-Tolerance', 'Kemampuan untuk menunjukkan toleransi terhadap perbedaan pendapat, kepercayaan, dan nilai-nilai, menciptakan lingkungan yang saling menghargai dan inklusif.', 'SOC'),
    (68, 'Compromise Building', 'Kemampuan untuk mencari dan menemukan titik temu yang dapat diterima oleh semua pihak dalam negosiasi.', 'SOC'),
    (69, 'Win-Win Agreement', 'Kemampuan untuk mencapai kesepakatan yang menguntungkan bagi semua pihak yang terlibat dalam negosiasi.', 'SOC'),
    (70, 'Leadership-Persuasion', 'Penguasaan berbagai teknik dan taktik persuasi, seperti storytelling, pembentukan kesepakatan, dan menunjukkan empati, yang dapat digunakan untuk mempengaruhi dan membujuk orang lain.', 'LEAD'),
    (71, 'Persuasion GPQ', 'Penguasaan berbagai teknik dan taktik persuasi, seperti storytelling, pembentukan kesepakatan, dan menunjukkan empati, yang dapat digunakan untuk mempengaruhi dan membujuk orang lain.', 'LEAD'),
    (72, 'Leadership-Influence', 'Kemampuan untuk menginspirasi, memotivasi, dan membimbing orang lain dalam mencapai tujuan bersama melalui pengaruh dan persuasi. Kepemimpinan dalam pengaruh melibatkan pemanfaatan wewenang, kepercayaan, dan komunikasi yang efektif untuk menciptakan lingkungan yang mendukung dan kooperatif.', 'LEAD'),
    (73, 'Leadership-Situational', 'Kemampuan untuk menyesuaikan gaya kepemimpinan sesuai dengan situasi, karakteristik anggota tim, dan kebutuhan tugas atau proyek, sehingga dapat mengarahkan tim secara efektif dan mencapai tujuan yang diinginkan.', 'LEAD'),
    (74, 'Leadership-Relationship', 'Kemampuan untuk membentuk hubungan yang kuat dan saling mendukung dengan orang lain, baik dalam tim, organisasi, atau jaringan luas. Penetapan dukungan memungkinkan seseorang untuk mempengaruhi keputusan dan menggerakkan orang lain untuk mencapai tujuan bersama.', 'LEAD'),
    (75, 'Task Prioritization', 'Kemampuan untuk mengatur tugas berdasarkan prioritas yang telah ditentukan, memastikan pekerjaan yang paling penting dan mendesak diselesaikan terlebih dahulu.', 'TASK'),
    (76, 'Task Organization', 'Kemampuan untuk mengorganisir tugas dan kegiatan dengan cara yang efisien dan efektif, termasuk delegasi tanggung jawab dan koordinasi tim.', 'TASK'),
    (77, 'Plan Development', 'Kemampuan untuk merumuskan rencana yang mencakup langkah-langkah, sumber daya, dan waktu yang diperlukan untuk mencapai tujuan yang telah ditetapkan.', 'TASK'),
    (78, 'Plan Adjustment', 'Kemampuan untuk menyesuaikan rencana yang ada berdasarkan perubahan kondisi, prioritas, atau informasi baru untuk memastikan keberhasilan dalam mencapai tujuan.', 'TASK'),
    (79, 'Resource Allocation', 'Kemampuan untuk mengalokasikan sumber daya yang ada, seperti tenaga kerja, anggaran, dan peralatan, sesuai dengan prioritas yang telah ditetapkan.', 'TASK'),
    (80, 'Quality Control', 'Kemampuan untuk memastikan standar kualitas yang telah ditetapkan dipenuhi dan diterapkan secara konsisten dalam setiap aspek pekerjaan.', 'TASK'),
    (81, 'Progress Monitoring', 'Kemampuan untuk secara teratur memantau kemajuan terhadap pencapaian tujuan, mengumpulkan data, dan melacak kinerja.', 'TASK'),
    (82, 'Controlling GPQ', 'Kemampuan untuk secara teratur memantau kemajuan terhadap pencapaian tujuan, mengumpulkan data, dan melacak kinerja.', 'TASK'),
    (83, 'KPI Setting', 'Kemampuan untuk menentukan indikator kinerja yang relevan dan dapat diukur untuk memantau kemajuan dan pencapaian tujuan.', 'TASK'),
    (84, 'Task Delegation', 'Kemampuan untuk mendelegasikan tugas dan wewenang kepada anggota tim dengan cara yang efektif dan efisien, memungkinkan mereka untuk bekerja secara mandiri dan memberikan kesempatan untuk mengembangkan keterampilan dan pengetahuan mereka.', 'TASK'),
    (85, 'Corrective Action', 'Kemampuan untuk mengidentifikasi dan mengimplementasikan tindakan korektif yang diperlukan untuk mengatasi masalah atau penyimpangan dari rencana yang ada.', 'TASK'),
    (86, 'Empowering and Supporting', 'Kemampuan untuk memberikan dukungan yang diperlukan kepada anggota tim saat menjalankan tugas yang telah didelegasikan, sekaligus memastikan kemajuan tugas tersebut untuk memastikan pencapaian tujuan yang diinginkan.', 'TASK'),
    (87, 'Self Assessment', 'Proses mengevaluasi keterampilan, pengetahuan, dan kompetensi yang dimiliki saat ini dan mengidentifikasi area yang memerlukan pengembangan atau perbaikan. Analisis kebutuhan pengembangan membantu seseorang untuk merencanakan dan menargetkan upaya pengembangan diri secara efektif.', 'DEV'),
    (88, 'People Assessment', 'Kemampuan untuk menilai kekuatan dan kelemahan individu dalam tim atau organisasi, serta mengidentifikasi area yang memerlukan pengembangan untuk mencapai tujuan bersama.', 'DEV'),
    (89, 'Development Plan', 'Merumuskan rencana yang terstruktur dan sistematis untuk mengembangkan keterampilan, pengetahuan, dan kompetensi yang dibutuhkan. Rencana pengembangan mencakup tujuan jangka pendek dan jangka panjang, strategi, sumber daya, dan jadwal untuk mencapai tujuan tersebut.', 'DEV'),
    (90, 'Development Action', 'Melaksanakan rencana pengembangan yang telah disusun dengan aktif mencari dan memanfaatkan peluang pengembangan, seperti pelatihan, pembelajaran mandiri, pengalaman kerja, atau dukungan dari mentor atau pelatih. Tindakan pengembangan melibatkan komitmen dan disiplin untuk menginvestasikan waktu dan usaha dalam proses pembelajaran.', 'DEV'),
    (91, 'Learning Environment', 'Kemampuan untuk menciptakan dan mempertahankan lingkungan yang mendukung dan mendorong pembelajaran, pertumbuhan, dan pengembangan bagi anggota tim atau individu, sehingga mereka dapat mencapai potensi penuh mereka dan berkontribusi secara efektif terhadap pencapaian tujuan organisasi atau tim.', 'DEV'),
    (92, 'Providing Feedback', 'Kemampuan untuk memberikan umpan balik yang konstruktif, jujur, dan tepat waktu kepada anggota tim atau individu untuk membantu mereka memahami kekuatan dan area yang perlu ditingkatkan, serta untuk mengarahkan mereka menuju perkembangan yang efektif.', 'DEV'),
    (93, 'Mentoring and Coaching', 'Kemampuan untuk membimbing, mendukung, dan memberikan nasihat kepada anggota tim atau individu dalam pengembangan keterampilan, pengetahuan, dan kompetensi yang diperlukan untuk meningkatkan kinerja dan mencapai tujuan.', 'DEV'),
    (94, 'Customer Relationships', 'Kemampuan untuk membangun hubungan yang kuat dan langgeng dengan pelanggan, menciptakan kesetiaan dan kepercayaan.', 'CUST'),
    (95, 'Identifying Customer Needs', 'Kemampuan untuk mengenali dan memahami kebutuhan dan harapan pelanggan.', 'CUST'),
    (96, 'Quality Customer Service', 'Kemampuan untuk menyediakan layanan yang konsisten dan berkualitas tinggi untuk memastikan kepuasan pelanggan dan retensi jangka panjang.', 'CUST'),
    (97, 'Customer Satisfaction Monitoring', 'Kemampuan untuk secara rutin memantau tingkat kepuasan pelanggan dan mengidentifikasi area yang memerlukan perbaikan.', 'CUST'),
    (98, 'Recognizing the Need for Change', 'Kemampuan untuk mengidentifikasi dan memahami kebutuhan untuk melakukan perubahan, baik dalam organisasi, tim, atau proses kerja, dengan tujuan untuk meningkatkan kinerja, efisiensi, dan mencapai tujuan yang diinginkan.', 'CHG'),
    (99, 'Planning for Change', 'Kemampuan untuk merancang rencana yang komprehensif dan realistis untuk mengimplementasikan perubahan yang diperlukan, termasuk langkah-langkah yang jelas, tanggung jawab, dan waktu yang diharapkan untuk mencapai tujuan perubahan.', 'CHG'),
    (100, 'Managing Uncertainty', 'Kemampuan untuk mengatasi ketidakpastian dan mengelola risiko yang mungkin muncul selama proses perubahan, termasuk meresapi kekhawatiran dan keberatan dari anggota tim atau pihak yang terkait, serta menemukan solusi yang efektif untuk mengatasi tantangan tersebut.', 'CHG'),
    (101, 'Evaluating the Impact of Change', 'Kemampuan untuk menilai dampak perubahan yang telah diimplementasikan, baik dalam hal kinerja, efisiensi, atau pencapaian tujuan, serta mengidentifikasi pelajaran yang dapat dipetik dari proses perubahan untuk meningkatkan pengelolaan perubahan di masa depan.', 'CHG'),
    (102, 'Marketing Understanding', 'Kemampuan untuk memahami konsep dan strategi pemasaran, termasuk segmentasi pasar, positioning, dan promosi.', 'PRO'),
    (103, 'Industry Understanding', 'Kemampuan untuk memahami dinamika dan tren industri, serta mengidentifikasi peluang dan tantangan dalam konteks bisnis.', 'PRO'),
    (104, 'Financial Understanding', 'Kemampuan untuk memahami konsep dan prinsip keuangan dalam bisnis, termasuk pengelolaan anggaran, pengendalian biaya, dan analisis laporan keuangan.', 'PRO'),
    (105, 'Business Strategy Understanding', 'Kemampuan untuk memahami dan menerapkan strategi bisnis dalam rangka mencapai tujuan organisasi.', 'PRO'),
    (106, 'Up-to-Date Technology Knowledge', 'Kesadaran akan perkembangan terbaru dalam teknologi dan kemampuan untuk mengadaptasi teknologi baru dalam konteks bisnis.', 'PRO'),
    (107, 'Software Proficiency', 'Kemampuan untuk menggunakan perangkat lunak yang relevan dengan efisien dan efektif.', 'PRO'),
    (108, 'Internet Navigation', 'Kemampuan untuk mencari, mengevaluasi, dan menggunakan informasi yang ditemukan di internet secara efektif.', 'PRO'),
    (109, 'Digital Communication', 'Kemampuan untuk berkomunikasi secara efektif dan etis melalui saluran digital.', 'PRO');
