-- Migration number: 0048 	 2025-03-27T05:30:35.511Z
CREATE TABLE mod_verbal_content (
    [id] INTEGER PRIMARY KEY,
    [mod_uuid] TEXT NOT NULL,
    [seq] INTEGER NOT NULL,
    [url] TEXT NOT NULL DEFAULT '',
    [content] TEXT NOT NULL DEFAULT '',
    [created] TEXT NOT NULL DEFAULT ((strftime('%Y-%m-%dT%H:%M:%fZ', 'now', 'utc'))),
    [updated] TEXT,
    UNIQUE (mod_uuid, seq)
);

CREATE INDEX idx_mod_verbal_content_seq ON mod_verbal_content (seq);
CREATE INDEX idx_mod_verbal_content_mod_uuid ON mod_verbal_content (mod_uuid);

CREATE TRIGGER update_mod_verbal_content AFTER UPDATE ON mod_verbal_content
BEGIN
	UPDATE mod_verbal_content SET updated = (strftime('%Y-%m-%dT%H:%M:%fZ', 'now', 'utc')) WHERE id=NEW.id;
END;

INSERT INTO mod_verbal_content (id, mod_uuid, seq, content) VALUES
    (1, 'a0ddaf8e-5120-4191-b2a0-10b55369b019', 1, '<p>Mohandas Karamchand Gandhi juga dipanggil Mahatma Gandhi adalah seorang pemimpin spiritual dan politikus dari India. Pada masa kehidupan Gandhi, India merupakan koloni Inggris dan Gandhi adalah salah seorang yang paling penting yang terlibat dalam Gerakan Kemerdekaan India. Dia adalah aktivis yang tidak menggunakan kekerasan, yang mengusung gerakan kemerdekaan melalui aksi demonstrasi damai.</p><p>Setelah lulus menjadi pengacara, Gandhi pergi ke Afrika Selatan, sebuah koloni Inggris, di mana dia mengalami diskriminasi ras yang dinamakan apartheid; dan dia kemudian memutuskan untuk menjadi seorang aktivis politik agar dapat mengubah hukum-hukum yang diskriminatif tersebut. Gandhi pun membentuk sebuah gerakan non-kekerasan.</p><p>Kembali ke India, dia membantu proses kemerdekaan India dari jajahan Inggris; hal ini memberikan inspirasi bagi rakyat di koloni-koloni lainnya agar berjuang mendapatkan kemerdekaannya, dan akhirnya memecah Kemaharajaan Britania untuk kemudian membentuk Persemakmuran.</p><p>Gelar Mahatma sering disalahartikan di Barat sebagai nama kecil Gandhi. Mahatma merupakan sebuah kata dalam bahasa Sanskerta yang berasal dari maha (berarti besar) dan atma (berarti Jiwa). Rabindranath Tagore disebutkan sebagai orang yang pertama kali memberikan gelar tersebut untuk Gandhi. Dalam otobiografinya, Gandhi mengatakan bahwa dia tidak pernah menyukai dan sering terluka oleh gelar itu.</p>'),
    (2, 'a0ddaf8e-5120-4191-b2a0-10b55369b019', 2, '<p>Pasar valuta asing atau disingkat valas adalah suatu jenis perdagangan atau transaksi yang memperdagangkan mata uang suatu negara terhadap mata uang negara lainnya yang melibatkan pasar-pasar uang utama.</p><p>Pergerakan pasar valuta asing berputar mulai dari pasar Selandia Baru dan Australia: pukul 05.00– 14.00 WIB, terus ke pasar Asia yaitu Jepang, Singapura, dan Hongkong: pukul 07.00–16.00 WIB, ke pasar Eropa yaitu Jerman dan Inggris: pukul 13.00–22.00 WIB, sampai ke pasar Amerika Serikat: pukul 20.30–10.30 WIB. Dalam perkembangan sejarahnya, bank sentral milik negara-negara dengan cadangan mata uang asing yang terbesar sekalipun dapat dikalahkan oleh kekuatan pasar valuta asing yang bebas.</p><p>Menurut survei BIS (<em>Bank International for Settlement</em>), yang dilakukan pada akhir tahun 2013, nilai transaksi pasar valuta asing mencapai lebih dari USD$5,3 triliun per harinya.</p><p>Mengingat tingkat likuiditas dan percepatan pergerakan harga yang tinggi, valuta asing juga telah menjadi alternatif bisnis yang populer karena ROI (<em>return on investment</em> atau tingkat pengembalian investasi) serta laba yang akan didapat bisa melebihi rata-rata perdagangan pada umumnya; dan akibat pergerakan yang cepat tersebut, maka pasar valuta asing juga memiliki risiko yang sangat tinggi.</p>'),
    (3, 'a0ddaf8e-5120-4191-b2a0-10b55369b019', 3, '<p>Gunung Tambora terletak di pulau Sumbawa yang merupakan bagian dari kepulauan Nusa Tenggara. Gunung ini adalah bagian dari busur Sunda, tali dari kepulauan vulkanik yang membentuk rantai selatan kepulauan Indonesia. Tambora membentuk semenanjungnya sendiri di pulau Sumbawa yang disebut semenanjung Sanggar.</p><p>Tambora terbentuk oleh zona subduksi di bawahnya, dan hal ini meningkatkan ketinggian Tambora sampai 4.300 m yang membuat gunung ini pernah menjadi salah satu puncak tertinggi di Nusantara. Aktivitas vulkanik gunung berapi ini mencapai puncaknya pada bulan April tahun 1815 ketika meletus, dan menjadi letusan terbesar sejak letusan danau Taupo pada tahun 181.</p><p>Letusan gunung ini terdengar hingga pulau Sumatra dan abu vulkaniknya jatuh di Kalimantan, Sulawesi, Jawa dan Maluku. Letusan gunung ini menyebabkan kematian hingga tidak kurang dari 71.000 orang dengan 11.000—12.000 di antaranya terbunuh secara langsung akibat dari letusan tersebut.</p><p>Lebih dari itu, letusan gunung ini menyebabkan perubahan iklim dunia; terjadi perubahan drastis cuaca di Amerika Utara dan Eropa karena debu yang dihasilkan dari letusan Tambora; dan akibatnya banyak panen yang gagal dan kematian ternak di Belahan Utara yang menyebabkan terjadinya kelaparan terburuk pada abad ke-19.</p>'),
    (4, 'a0ddaf8e-5120-4191-b2a0-10b55369b019', 4, '<p>Perangkat perusak (bahasa Inggris: <em>malware</em>, berasal dari kata <em>malicious</em> dan <em>software</em>) adalah perangkat lunak (<em>software</em>) yang diciptakan untuk menyusup atau merusak sistem komputer, peladen (<em>server</em>), atau jejaring komputer tanpa izin termaklum (<em>informed consent</em>) dari pemilik. Istilah ini adalah istilah umum yang dipakai oleh pakar komputer untuk mengartikan berbagai macam perangkat lunak atau kode perangkat lunak yang mengganggu atau mengusik.</p><p>Perangkat lunak dianggap sebagai perangkat perusakberdasarkan maksud dari pembuat dan bukan berdasarkan ciri-ciri tertentu. Perangkat perusak mencakup virus komputer, cacing komputer, kuda Troya (<em>Trojan horse</em>), perangkat pengintai (<em>spyware</em>), perangkat iklan (<em>adware</em>) yang tak jujur, perangkat jahat (<em>crimeware</em>) dan perangkat lunak lainnya yang berniat jahat dan tidak diinginkan, seperti dua contoh dibawah ini:</p><ul><li>Bancos: pencuri informasi yang menunggu pengguna untuk membuka situs perbankan lalu mengalihkan halaman situs bank yang asli ke yang palsu untuk mencuri informasi yang peka.</li><li>Gator: perangkat pengintai yang memantau kebiasaan penjelajahan web dengan rahasia, dan mengunggah (<em>upload</em>) data ke peladen untuk penyelidikan. Kemudian, menyajikan iklan sembul sendiri yang disasarkan (<em>targeted pop-up ads</em>).</li></ul>'),
    (5, 'a0ddaf8e-5120-4191-b2a0-10b55369b019', 5, '<p>Rendang atau randang adalah masakan daging bercita rasa pedas yang menggunakan campuran dari berbagai bumbu dan rempah-rempah. Masakan ini dihasilkan dari proses memasak yang dipanaskan berulang-ulang dengan santan kelapa.</p><p>Proses memasaknya memakan waktu berjam-jam (biasanya sekitar empat jam) hingga kering dan berwarna hitam pekat. Dalam suhu ruangan, rendang dapat bertahan hingga berminggu- minggu. Rendang yang dimasak dalam waktu yang lebih singkat dan santannya belum mengering disebut kalio, berwarna coklat terang keemasan.</p><p>Rendang dapat ditemukan di Rumah Makan Padang di seluruh dunia. Masakan ini populer di kalangan masyarakat Indonesia dan negara-negara di Asia Tenggara, seperti Malaysia, Singapura, Brunei, Filipina, dan Thailand. Di daerah asalnya, Minangkabau, rendang disajikan dalam berbagai upacara adat dan perhelatan istimewa.</p><p>Meskipun rendang merupakan masakan tradisional Minangkabau secara umum, masing-masing daerah di Minangkabau memiliki teknik memasak dan penggunaan bumbu yang berbeda. Pada tahun 2011, rendang dinobatkan sebagai hidangan peringkat pertama dalam daftar <em>World&#39;s 50 Most Delicious Foods</em> (50 Hidangan Terlezat Dunia) yang digelar oleh <em>CNN International</em>.</p>');
