export const HTMX_EVENTS = {
	MODULE_GetIntraySection: "MODULE_GetIntraySection",
	MODULE_GetCaseAnalysMainContent: "MODULE_GetCaseAnalysMainContent",
	MODULE_GetCaseAnalysAssignmentList: "MODULE_GetCaseAnalysAssignmentList",
	ACES_GetOrganizationTable: "ACES_GetOrganizationTable",
	ACES_OrganizationCreated: "ACES_OrganizationCreated",
	ACES_BatchModuleMutation: "ACES_BatchModuleMutation",
	ACES_BatchPersonMutation: "ACES_BatchPersonMutation",
	ACES_Regrouping: "ACES_Regrouping",
	ACES_GetAssessorBucketAllocation: "ACES_GetAssessorBucketAllocation",
	ACES_GetBatchAssessorTable: "ACES_GetBatchAssessorTable",
	ACES_DiscManualPair: "ACES_DiscManualPair",
	ACES_FaceManualPair: "ACES_FaceManualPair",
	ACES_CaseManualPair: "ACES_CaseManualPair",
	ACES_DeploymentBatchTime: "ACES_DeploymentBatchTime",
	ACES_DeploymentTime1: "ACES_DeploymentTime1",
	ACES_DeploymentTime2: "ACES_DeploymentTime2",
	ACES_DeploymentTime3: "ACES_DeploymentTime3",
	ACES_DeploymentTime4: "ACES_DeploymentTime4",
}